#
#       Filename:  Makefile
#
#        Version:  1.0
#        Created:  03/26/2018 09:56:18 PM
#       Revision:  none
#
#         Author:  Bo Salvadalena, bxsalvadalena01@students.everettcc.edu
#

CC = /usr/bin/cc
CFLAGS =
CPPFLAGS =
LDFLAGS =

PROG = exercise6-3

.SUFFIXES : .o .c

all : 
	${CC} main.c bitree/bitree.[ch] -o ${PROG}.out

clean :
	rm ${PROG}.out
